/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.java.apis;

import io.kubernetes.java.ApiException;
import io.kubernetes.java.models.UnversionedAPIResourceList;
import io.kubernetes.java.models.UnversionedPatch;
import io.kubernetes.java.models.UnversionedStatus;
import io.kubernetes.java.models.V1DeleteOptions;
import io.kubernetes.java.models.V1beta1DaemonSet;
import io.kubernetes.java.models.V1beta1DaemonSetList;
import io.kubernetes.java.models.V1beta1Deployment;
import io.kubernetes.java.models.V1beta1DeploymentList;
import io.kubernetes.java.models.V1beta1DeploymentRollback;
import io.kubernetes.java.models.V1beta1HorizontalPodAutoscaler;
import io.kubernetes.java.models.V1beta1HorizontalPodAutoscalerList;
import io.kubernetes.java.models.V1beta1Ingress;
import io.kubernetes.java.models.V1beta1IngressList;
import io.kubernetes.java.models.V1beta1Job;
import io.kubernetes.java.models.V1beta1JobList;
import io.kubernetes.java.models.V1beta1NetworkPolicy;
import io.kubernetes.java.models.V1beta1NetworkPolicyList;
import io.kubernetes.java.models.V1beta1ReplicaSet;
import io.kubernetes.java.models.V1beta1ReplicaSetList;
import io.kubernetes.java.models.V1beta1Scale;
import io.kubernetes.java.models.V1beta1ThirdPartyResource;
import io.kubernetes.java.models.V1beta1ThirdPartyResourceList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExtensionsV1beta1Api
 */
@Ignore
public class ExtensionsV1beta1ApiTest {

    private final ExtensionsV1beta1Api api = new ExtensionsV1beta1Api();

    
    /**
     * 
     *
     * create a DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedDaemonSetTest() throws ApiException {
        String namespace = null;
        V1beta1DaemonSet body = null;
        String pretty = null;
        V1beta1DaemonSet response = api.createNamespacedDaemonSet(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedDeploymentTest() throws ApiException {
        String namespace = null;
        V1beta1Deployment body = null;
        String pretty = null;
        V1beta1Deployment response = api.createNamespacedDeployment(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create rollback of a DeploymentRollback
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedDeploymentRollbackRollbackTest() throws ApiException {
        V1beta1DeploymentRollback body = null;
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1DeploymentRollback response = api.createNamespacedDeploymentRollbackRollback(body, name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedHorizontalPodAutoscalerTest() throws ApiException {
        String namespace = null;
        V1beta1HorizontalPodAutoscaler body = null;
        String pretty = null;
        V1beta1HorizontalPodAutoscaler response = api.createNamespacedHorizontalPodAutoscaler(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create an Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedIngressTest() throws ApiException {
        String namespace = null;
        V1beta1Ingress body = null;
        String pretty = null;
        V1beta1Ingress response = api.createNamespacedIngress(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedJobTest() throws ApiException {
        String namespace = null;
        V1beta1Job body = null;
        String pretty = null;
        V1beta1Job response = api.createNamespacedJob(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedNetworkPolicyTest() throws ApiException {
        String namespace = null;
        V1beta1NetworkPolicy body = null;
        String pretty = null;
        V1beta1NetworkPolicy response = api.createNamespacedNetworkPolicy(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedReplicaSetTest() throws ApiException {
        String namespace = null;
        V1beta1ReplicaSet body = null;
        String pretty = null;
        V1beta1ReplicaSet response = api.createNamespacedReplicaSet(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a ThirdPartyResource
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createThirdPartyResourceTest() throws ApiException {
        V1beta1ThirdPartyResource body = null;
        String pretty = null;
        V1beta1ThirdPartyResource response = api.createThirdPartyResource(body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionNamespacedDaemonSetTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionNamespacedDaemonSet(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionNamespacedDeploymentTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionNamespacedDeployment(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionNamespacedHorizontalPodAutoscalerTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionNamespacedHorizontalPodAutoscaler(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionNamespacedIngressTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionNamespacedIngress(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionNamespacedJobTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionNamespacedJob(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionNamespacedNetworkPolicyTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionNamespacedNetworkPolicy(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionNamespacedReplicaSetTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionNamespacedReplicaSet(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of ThirdPartyResource
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCollectionThirdPartyResourceTest() throws ApiException {
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        UnversionedStatus response = api.deleteCollectionThirdPartyResource(pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedDaemonSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteNamespacedDaemonSet(name, namespace, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedDeploymentTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteNamespacedDeployment(name, namespace, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedHorizontalPodAutoscalerTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteNamespacedHorizontalPodAutoscaler(name, namespace, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete an Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedIngressTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteNamespacedIngress(name, namespace, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteNamespacedJob(name, namespace, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedNetworkPolicyTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteNamespacedNetworkPolicy(name, namespace, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedReplicaSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteNamespacedReplicaSet(name, namespace, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a ThirdPartyResource
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteThirdPartyResourceTest() throws ApiException {
        String name = null;
        V1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        UnversionedStatus response = api.deleteThirdPartyResource(name, body, pretty, gracePeriodSeconds, orphanDependents);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get available resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIResourcesTest() throws ApiException {
        UnversionedAPIResourceList response = api.getAPIResources();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDaemonSetForAllNamespacesTest() throws ApiException {
        String fieldSelector = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1DaemonSetList response = api.listDaemonSetForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDeploymentForAllNamespacesTest() throws ApiException {
        String fieldSelector = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1DeploymentList response = api.listDeploymentForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listHorizontalPodAutoscalerForAllNamespacesTest() throws ApiException {
        String fieldSelector = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1HorizontalPodAutoscalerList response = api.listHorizontalPodAutoscalerForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listIngressForAllNamespacesTest() throws ApiException {
        String fieldSelector = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1IngressList response = api.listIngressForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listJobForAllNamespacesTest() throws ApiException {
        String fieldSelector = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1JobList response = api.listJobForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNamespacedDaemonSetTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1DaemonSetList response = api.listNamespacedDaemonSet(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNamespacedDeploymentTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1DeploymentList response = api.listNamespacedDeployment(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNamespacedHorizontalPodAutoscalerTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1HorizontalPodAutoscalerList response = api.listNamespacedHorizontalPodAutoscaler(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNamespacedIngressTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1IngressList response = api.listNamespacedIngress(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNamespacedJobTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1JobList response = api.listNamespacedJob(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNamespacedNetworkPolicyTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1NetworkPolicyList response = api.listNamespacedNetworkPolicy(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNamespacedReplicaSetTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1ReplicaSetList response = api.listNamespacedReplicaSet(namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNetworkPolicyForAllNamespacesTest() throws ApiException {
        String fieldSelector = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1NetworkPolicyList response = api.listNetworkPolicyForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listReplicaSetForAllNamespacesTest() throws ApiException {
        String fieldSelector = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1ReplicaSetList response = api.listReplicaSetForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind ThirdPartyResource
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listThirdPartyResourceTest() throws ApiException {
        String pretty = null;
        String fieldSelector = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        V1beta1ThirdPartyResourceList response = api.listThirdPartyResource(pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedDaemonSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1DaemonSet response = api.patchNamespacedDaemonSet(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedDaemonSetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1DaemonSet response = api.patchNamespacedDaemonSetStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedDeploymentTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Deployment response = api.patchNamespacedDeployment(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedDeploymentStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Deployment response = api.patchNamespacedDeploymentStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedDeploymentsScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Scale response = api.patchNamespacedDeploymentsScale(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedHorizontalPodAutoscalerTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1HorizontalPodAutoscaler response = api.patchNamespacedHorizontalPodAutoscaler(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedHorizontalPodAutoscalerStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1HorizontalPodAutoscaler response = api.patchNamespacedHorizontalPodAutoscalerStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedIngressTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Ingress response = api.patchNamespacedIngress(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedIngressStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Ingress response = api.patchNamespacedIngressStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Job response = api.patchNamespacedJob(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedJobStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Job response = api.patchNamespacedJobStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedNetworkPolicyTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1NetworkPolicy response = api.patchNamespacedNetworkPolicy(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedReplicaSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1ReplicaSet response = api.patchNamespacedReplicaSet(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedReplicaSetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1ReplicaSet response = api.patchNamespacedReplicaSetStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedReplicasetsScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Scale response = api.patchNamespacedReplicasetsScale(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchNamespacedReplicationcontrollersScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1Scale response = api.patchNamespacedReplicationcontrollersScale(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified ThirdPartyResource
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchThirdPartyResourceTest() throws ApiException {
        String name = null;
        UnversionedPatch body = null;
        String pretty = null;
        V1beta1ThirdPartyResource response = api.patchThirdPartyResource(name, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedDaemonSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1DaemonSet response = api.readNamespacedDaemonSet(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedDaemonSetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1DaemonSet response = api.readNamespacedDaemonSetStatus(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedDeploymentTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1Deployment response = api.readNamespacedDeployment(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedDeploymentStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1Deployment response = api.readNamespacedDeploymentStatus(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedDeploymentsScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1Scale response = api.readNamespacedDeploymentsScale(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedHorizontalPodAutoscalerTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1HorizontalPodAutoscaler response = api.readNamespacedHorizontalPodAutoscaler(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedHorizontalPodAutoscalerStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1HorizontalPodAutoscaler response = api.readNamespacedHorizontalPodAutoscalerStatus(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedIngressTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1Ingress response = api.readNamespacedIngress(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedIngressStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1Ingress response = api.readNamespacedIngressStatus(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1Job response = api.readNamespacedJob(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedJobStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1Job response = api.readNamespacedJobStatus(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedNetworkPolicyTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1NetworkPolicy response = api.readNamespacedNetworkPolicy(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedReplicaSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1ReplicaSet response = api.readNamespacedReplicaSet(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedReplicaSetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1ReplicaSet response = api.readNamespacedReplicaSetStatus(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedReplicasetsScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1Scale response = api.readNamespacedReplicasetsScale(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readNamespacedReplicationcontrollersScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        V1beta1Scale response = api.readNamespacedReplicationcontrollersScale(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified ThirdPartyResource
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readThirdPartyResourceTest() throws ApiException {
        String name = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        V1beta1ThirdPartyResource response = api.readThirdPartyResource(name, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedDaemonSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1DaemonSet body = null;
        String pretty = null;
        V1beta1DaemonSet response = api.replaceNamespacedDaemonSet(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified DaemonSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedDaemonSetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1DaemonSet body = null;
        String pretty = null;
        V1beta1DaemonSet response = api.replaceNamespacedDaemonSetStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedDeploymentTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Deployment body = null;
        String pretty = null;
        V1beta1Deployment response = api.replaceNamespacedDeployment(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified Deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedDeploymentStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Deployment body = null;
        String pretty = null;
        V1beta1Deployment response = api.replaceNamespacedDeploymentStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedDeploymentsScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Scale body = null;
        String pretty = null;
        V1beta1Scale response = api.replaceNamespacedDeploymentsScale(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedHorizontalPodAutoscalerTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1HorizontalPodAutoscaler body = null;
        String pretty = null;
        V1beta1HorizontalPodAutoscaler response = api.replaceNamespacedHorizontalPodAutoscaler(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified HorizontalPodAutoscaler
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedHorizontalPodAutoscalerStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1HorizontalPodAutoscaler body = null;
        String pretty = null;
        V1beta1HorizontalPodAutoscaler response = api.replaceNamespacedHorizontalPodAutoscalerStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedIngressTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Ingress body = null;
        String pretty = null;
        V1beta1Ingress response = api.replaceNamespacedIngress(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified Ingress
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedIngressStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Ingress body = null;
        String pretty = null;
        V1beta1Ingress response = api.replaceNamespacedIngressStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Job body = null;
        String pretty = null;
        V1beta1Job response = api.replaceNamespacedJob(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedJobStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Job body = null;
        String pretty = null;
        V1beta1Job response = api.replaceNamespacedJobStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified NetworkPolicy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedNetworkPolicyTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1NetworkPolicy body = null;
        String pretty = null;
        V1beta1NetworkPolicy response = api.replaceNamespacedNetworkPolicy(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedReplicaSetTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1ReplicaSet body = null;
        String pretty = null;
        V1beta1ReplicaSet response = api.replaceNamespacedReplicaSet(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified ReplicaSet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedReplicaSetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1ReplicaSet body = null;
        String pretty = null;
        V1beta1ReplicaSet response = api.replaceNamespacedReplicaSetStatus(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedReplicasetsScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Scale body = null;
        String pretty = null;
        V1beta1Scale response = api.replaceNamespacedReplicasetsScale(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace scale of the specified Scale
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceNamespacedReplicationcontrollersScaleTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1beta1Scale body = null;
        String pretty = null;
        V1beta1Scale response = api.replaceNamespacedReplicationcontrollersScale(name, namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified ThirdPartyResource
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceThirdPartyResourceTest() throws ApiException {
        String name = null;
        V1beta1ThirdPartyResource body = null;
        String pretty = null;
        V1beta1ThirdPartyResource response = api.replaceThirdPartyResource(name, body, pretty);

        // TODO: test validations
    }
    
}
