/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.java.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * APIResource specifies the name of a resource and whether it is namespaced.
 */
@ApiModel(description = "APIResource specifies the name of a resource and whether it is namespaced.")

public class UnversionedAPIResource {
  @SerializedName("kind")
  private String kind = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("namespaced")
  private Boolean namespaced = null;

  public UnversionedAPIResource kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo')
   * @return kind
  **/
  @ApiModelProperty(example = "null", required = true, value = "kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo')")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public UnversionedAPIResource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name is the name of the resource.
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "name is the name of the resource.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UnversionedAPIResource namespaced(Boolean namespaced) {
    this.namespaced = namespaced;
    return this;
  }

   /**
   * namespaced indicates if a resource is namespaced or not.
   * @return namespaced
  **/
  @ApiModelProperty(example = "null", required = true, value = "namespaced indicates if a resource is namespaced or not.")
  public Boolean getNamespaced() {
    return namespaced;
  }

  public void setNamespaced(Boolean namespaced) {
    this.namespaced = namespaced;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnversionedAPIResource unversionedAPIResource = (UnversionedAPIResource) o;
    return Objects.equals(this.kind, unversionedAPIResource.kind) &&
        Objects.equals(this.name, unversionedAPIResource.name) &&
        Objects.equals(this.namespaced, unversionedAPIResource.namespaced);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, name, namespaced);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnversionedAPIResource {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespaced: ").append(toIndentedString(namespaced)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

