/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.java.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.kubernetes.java.models.V1ObjectMeta;
import io.kubernetes.java.models.V1beta1HorizontalPodAutoscalerSpec;
import io.kubernetes.java.models.V1beta1HorizontalPodAutoscalerStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * configuration of a horizontal pod autoscaler.
 */
@ApiModel(description = "configuration of a horizontal pod autoscaler.")

public class V1beta1HorizontalPodAutoscaler {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private V1ObjectMeta metadata = null;

  @SerializedName("spec")
  private V1beta1HorizontalPodAutoscalerSpec spec = null;

  @SerializedName("status")
  private V1beta1HorizontalPodAutoscalerStatus status = null;

  public V1beta1HorizontalPodAutoscaler apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(example = "null", value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public V1beta1HorizontalPodAutoscaler kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(example = "null", value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public V1beta1HorizontalPodAutoscaler metadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Standard object metadata. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "Standard object metadata. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata")
  public V1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public V1beta1HorizontalPodAutoscaler spec(V1beta1HorizontalPodAutoscalerSpec spec) {
    this.spec = spec;
    return this;
  }

   /**
   * behaviour of autoscaler. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#spec-and-status.
   * @return spec
  **/
  @ApiModelProperty(example = "null", value = "behaviour of autoscaler. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#spec-and-status.")
  public V1beta1HorizontalPodAutoscalerSpec getSpec() {
    return spec;
  }

  public void setSpec(V1beta1HorizontalPodAutoscalerSpec spec) {
    this.spec = spec;
  }

  public V1beta1HorizontalPodAutoscaler status(V1beta1HorizontalPodAutoscalerStatus status) {
    this.status = status;
    return this;
  }

   /**
   * current information about the autoscaler.
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "current information about the autoscaler.")
  public V1beta1HorizontalPodAutoscalerStatus getStatus() {
    return status;
  }

  public void setStatus(V1beta1HorizontalPodAutoscalerStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1HorizontalPodAutoscaler v1beta1HorizontalPodAutoscaler = (V1beta1HorizontalPodAutoscaler) o;
    return Objects.equals(this.apiVersion, v1beta1HorizontalPodAutoscaler.apiVersion) &&
        Objects.equals(this.kind, v1beta1HorizontalPodAutoscaler.kind) &&
        Objects.equals(this.metadata, v1beta1HorizontalPodAutoscaler.metadata) &&
        Objects.equals(this.spec, v1beta1HorizontalPodAutoscaler.spec) &&
        Objects.equals(this.status, v1beta1HorizontalPodAutoscaler.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1HorizontalPodAutoscaler {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

