/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.java.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.kubernetes.java.models.ResourceQuantity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ResourceQuotaStatus defines the enforced hard limits and observed use.
 */
@ApiModel(description = "ResourceQuotaStatus defines the enforced hard limits and observed use.")

public class V1ResourceQuotaStatus {
  @SerializedName("hard")
  private Map<String, ResourceQuantity> hard = new HashMap<String, ResourceQuantity>();

  @SerializedName("used")
  private Map<String, ResourceQuantity> used = new HashMap<String, ResourceQuantity>();

  public V1ResourceQuotaStatus hard(Map<String, ResourceQuantity> hard) {
    this.hard = hard;
    return this;
  }

  public V1ResourceQuotaStatus putHardItem(String key, ResourceQuantity hardItem) {
    this.hard.put(key, hardItem);
    return this;
  }

   /**
   * Hard is the set of enforced hard limits for each named resource. More info: http://releases.k8s.io/HEAD/docs/design/admission_control_resource_quota.md#admissioncontrol-plugin-resourcequota
   * @return hard
  **/
  @ApiModelProperty(example = "null", value = "Hard is the set of enforced hard limits for each named resource. More info: http://releases.k8s.io/HEAD/docs/design/admission_control_resource_quota.md#admissioncontrol-plugin-resourcequota")
  public Map<String, ResourceQuantity> getHard() {
    return hard;
  }

  public void setHard(Map<String, ResourceQuantity> hard) {
    this.hard = hard;
  }

  public V1ResourceQuotaStatus used(Map<String, ResourceQuantity> used) {
    this.used = used;
    return this;
  }

  public V1ResourceQuotaStatus putUsedItem(String key, ResourceQuantity usedItem) {
    this.used.put(key, usedItem);
    return this;
  }

   /**
   * Used is the current observed total usage of the resource in the namespace.
   * @return used
  **/
  @ApiModelProperty(example = "null", value = "Used is the current observed total usage of the resource in the namespace.")
  public Map<String, ResourceQuantity> getUsed() {
    return used;
  }

  public void setUsed(Map<String, ResourceQuantity> used) {
    this.used = used;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ResourceQuotaStatus v1ResourceQuotaStatus = (V1ResourceQuotaStatus) o;
    return Objects.equals(this.hard, v1ResourceQuotaStatus.hard) &&
        Objects.equals(this.used, v1ResourceQuotaStatus.used);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hard, used);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ResourceQuotaStatus {\n");
    
    sb.append("    hard: ").append(toIndentedString(hard)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

